POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "No more",
  "author": "Helle Esimerkkinen", 
  "url": "https://www.nomore.com", 
  "likes": 0,
  "createdbyuserid": null
}